sudo: required
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .
  - export NUMBA_DISABLE_JIT=1  # Disable JIT

script:
  - pytest --cov

after_success:
  - codecov

notifications:
    email: raphaelvallat9@gmail.com
