build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64
      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA% %PYTHON_ARCH%"

install:
  # ------------------- PYTHON ENVIRONNEMENT -------------------
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n testenv python=%PYTHON_VERSION% numpy scipy matplotlib pip cython"
  - activate test_env
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install .

test_script:
  - "pytest"
